export const PTS = {
  age: { y: -10, vy: -20, m: 8, vm: 12, unknown: -2 },
  ssl: { v: 10, e: -18, p: -18, h: -22, es: -4, unknown: -5 },
  bl: { l: -30, c: 6 },
  ipInUrl: -15,
  urlAi: {
    ph90: -25,
    ph70: -15,
    ph50: -8,
    lh90: 8,
    lh70: 3,
    error: -2,
    neutral: 0,
  },
  contentAi: {
    phChunkHighConf: -8,
    phChunkMedConf: -4,
    phChunkLowConf: -2,
    manyPhishingChunksPenalty: -10,
    noProblemDetected: 5,
    noContentOrError: -1,
  },
  whoisPrivacy: { enabled: -2, explicitProblem: -5 },
  dnsMx: { missingForShop: -5, presentForShop: 2, notApplicable: 0 },
};
